name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ocaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4"

      - run: opam install . --deps-only --with-test -y

      - run: opam exec -- dune test

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cargo test
        working-directory: rust
